[package]
name = "post-notes"
description = "Building a cute digital garden."
version = "0.1.1"
edition = "2024"

[dependencies]
tokio = { version = "1", features = [
  "rt",
  "rt-multi-thread",
  "macros",
  "sync",
  "fs",
] }
tokio-macros = "2"
tokio-stream = "0.1"
anyhow = "1.0"
regex = "1.11"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-scribe = "0.2"
markdown = "1"
config = "0.15"
clap = { version = "4.5", features = ["derive"] }
tera = { version = "2", features = ["glob_fs"] }
rayon = "1.10"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
derive_more = { version = "2.0", features = ["display"] }

[dev-dependencies]
pretty_assertions = "1.4"
criterion = { version = "0.8", features = ["html_reports"] }

[[bench]]
name = "pipeline"
harness = false
